version: '3.5'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER:root
      - POSTGRES_PASSWORD:root
      - POSTGRES_DB:db_certificate-reader
    expose:
      - "5432"
    ports:
      - "5432:5432"
